### ISSUE TITLE
Can't install libstdc++

### ISSUE THREAD

**Issue by mikaoelitiana** [bitwalker/alpine-erlang#13]
After recent update, I started to experiment package installation issue on my build process. I have the following instructions on Dockerfile : 

```
FROM bitwalker/alpine-erlang:19.3

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ bash && \
    rm -rf /var/cache/apk/*

# ...
```

And it outputs the following error : 

```
ERROR: libstdc++-6.3.0-r4: Protocol error
```

Other packages are installed correctly.

**Comment by bitwalker** [comment]
That's a new one, I'll see what I can find

**Comment by bitwalker** [comment]
Seems like this is a repository issue, and not enough mirrors were available, try ensuring that all of the following variants are in `/etc/apk/repositories` (note that `<ALPINE_VERSION>` is my placeholder for whatever version of alpine your image is based on):

```
http://dl-1.alpinelinux.org/alpine/<ALPINE_VERSION>/main
http://dl-2.alpinelinux.org/alpine/<ALPINE_VERSION>/main
http://dl-3.alpinelinux.org/alpine/<ALPINE_VERSION>/main
http://dl-4.alpinelinux.org/alpine/<ALPINE_VERSION>/main
http://dl-5.alpinelinux.org/alpine/<ALPINE_VERSION>/main
```

**Comment by mikaoelitiana** [comment]
I added that to my image and it works appart of `dl-1` on `v3.6` which gives an error 
```
ERROR: http://dl-1.alpinelinux.org/alpine/v3.6/main: No such file or directory
```

Thanks!
