### ISSUE TITLE
Alpine Linux v3.8 

### ISSUE THREAD

**Issue by tomciopp** [bitwalker/alpine-erlang#31]
It looks like a new version of Alpine Linux was released a couple of weeks ago. Is there any reason to hold back on Alpine Linux 3.8?

**Comment by bitwalker** [comment]
I typically wait a bit on each new release of Alpine, just in case there are bugs remaining to be caught, but I will probably plan to make the switch this week.

**Comment by bitwalker** [comment]
I've pushed the switch to 3.8, and am publishing a new release now. Took a look through the open Alpine issues, and it seems like there is nothing of note. All the other major Alpine-based images have upgraded now, so I figure I should follow suit.
