### ISSUE TITLE
Some erlang headers are missing in 21.0.3 image

### ISSUE THREAD

**Issue by IceDragon200** [bitwalker/alpine-erlang#32]
I hope this is the right place...

Most notably `ssl_api.hrl`

I've tried installing the alpine erlang feature package (i.e `erlang-ssl`), however that downgrades erlang to 20.x, so no go there

I'm wonder if anyone else knows what's going on, or a possible solution

__Expected__

Several key erlang headers to exist

__Actual__

Several key erlang headers are missing

**Comment by bitwalker** [comment]
This is likely due to the stripping of the release - I've updated the image to skip all `.hrl` files, and only strip non-header sources. Let me know if you see further issues!

**Comment by IceDragon200** [comment]
Could you also trigger a rebuild of the `alpine-elixir` image? I forgot to mention yesterday that I tracked the issue down to `alpine-erlang` from using `alpine-elixir`, sorry for the trouble

**Comment by bitwalker** [comment]
Done!
