### ISSUE TITLE
Consider adding documentation/support for NIFS

### ISSUE THREAD

**Issue by dhonig** [bitwalker/alpine-erlang#46]
tag:  bitwalker/alpine-erlang:21.0.9

My Elixir project uses this as a base image to build its own elixir from source.  Our project uses exml, which in turn uses the Expat XML library via NIFS.

At first, we received the following error after releasing with Distillery:

```
api_1      | 2019-04-15 15:11:18.702898 crash_report        #{label=>{proc_lib,crash},report=>[[{initial_call,{supervisor,kernel,['Argument__1']}},{pid,<0.2463.0>},{registered_name,[]},{error_info,{exit,{on_load_function_failed,exml_nif},[{init,run_on_load_handlers,0,[]},{kernel,init,1,[{file,"kernel.erl"},{line,212}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,295}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[kernel_sup,<0.2437.0>]},{message_queue_len,0},{messages,[]},{links,[<0.2439.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,273}],[]]}
```

Careful troubleshooting revealed that we were missing a few libs:

```
RUN apk --no-cache add libc6-compat
RUN apk --no-cache add gcc
```

After adding these to our Dockerbuild the NIF error was resolved.   I need to get up to speed on using NIFs, but it would seem these libraries are commonly required to support NIFS and if that is the case then I would advocate for them being in the base image or at least mentioning them in the docs.   Troubleshooting this kind of error isn't the most fun thing :)

**Comment by tomciopp** [comment]
I don't think it's appropriate to add those libraries to the base image as it crosses the boundary of what this library intends to do and the needs of any specific application. While it would have benefitted you, almost everyone else who uses this package would see an increase in container size for no benefit. (I can empathize since I ran into a similar issue with erl-brotli)

Since you downloaded the NIF as part of another elixir package, I think the appropriate place to put the documentation would be there. This is the strategy employed by other packages. Then when you create your image, you will know what additional packages to add in your specific Dockerfile.

**Comment by bitwalker** [comment]
As @tomciopp has stated, this image is intended to be as small as possible (this is in part why we specify which OTP applications to build), one can easily base their own Dockerfile on `alpine-erlang` and add additional packages as needed, and in fact is the general intent of this image. Size of this image is of high importance, so we avoid including anything but the bare minimum.

That said, I think it is a fair point that we should document this, so I will add a note to the README to make sure people are aware that additional effort may be needed to support NIFs, or less commonly used OTP applications that are part of the standard library and are not included here by default.

**Comment by dhonig** [comment]
@tomciopp @bitwalker   Thanks for your review and consideration.   A quick note on the README.md is enough to make me happy.  Its not really an issue with exml as this is limited to users of the image.   Understanding the design goals of the image I concur with documenting this as a solution.  Hopefully we'll save someone an afternoon of strife testing the image for missing deps!
