### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by steffenix** [bitwalker/alpine-erlang#66]
Could be build an ARM version of this image and the elixir image, I would like to use the elixir base image on docker on a pi 4.

**Comment by tomciopp** [comment]
@bitwalker I don't think it would be too difficult to do this. Unless I am missing something I think you only need to make the following change to get things working on the Raspberry PI 4.

`FROM alpine:3.10.2 AS build` => `FROM arm64v8/alpine:3.10.2 AS build`

Do you want to make the change yourself and try it out?

**Comment by steffenix** [comment]
That would be good to have it published under the same name on docker hub, if @bitwalker isn't doing it I will build everything from alpine on my ci.

**Comment by bitwalker** [comment]
I'm doing a test run now, assuming there are no issues, I can publish it as `bitwalker/alpine-erlang-armv8:<TAG>`. Note that this would only support ARMv8 chipsets, so if other ARM targets need support, they would need to be evaluated separately
