### ISSUE TITLE
Question about erlang version

### ISSUE THREAD

**Issue by apischan** [bitwalker/alpine-erlang#7]
Is there any way to build image with erlang OTP-17.*?
When I just changing the tag name in
```
git clone -b OTP-19.3 --single-branch --depth 1 https://github.com/erlang/otp.git
```
to 
```
git clone -b OTP-17.5 --single-branch --depth 1 https://github.com/erlang/otp.git
```
it fails

**Comment by bitwalker** [comment]
Do you have the output of the error?

**Comment by apischan** [comment]
[here lines like]
 CC	obj/x86_64-unknown-linux-gnu/opt/smp/*
...
```
In file included from sys/common/erl_poll.c:55:0:
sys/common/erl_poll.c: In function 'conc_update_pollset':
sys/common/erl_poll.h:132:5: error: '__uint32_t' undeclared (first use in this function)
   ((__uint32_t) (EV))
     ^
sys/common/erl_poll.c:1145:24: note: in expansion of macro 'ERTS_POLL_EV_E2N'
     epe_templ.events = ERTS_POLL_EV_E2N(ps->fds_status[fd].events);
                        ^~~~~~~~~~~~~~~~
sys/common/erl_poll.h:132:5: note: each undeclared identifier is reported only once for each function it appears in
   ((__uint32_t) (EV))
     ^
sys/common/erl_poll.c:1145:24: note: in expansion of macro 'ERTS_POLL_EV_E2N'
     epe_templ.events = ERTS_POLL_EV_E2N(ps->fds_status[fd].events);
                        ^~~~~~~~~~~~~~~~
make[3]: *** [x86_64-unknown-linux-gnu/Makefile:723: obj/x86_64-unknown-linux-gnu/opt/smp/erl_poll.kp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/erlang-build/erts/emulator'
make[2]: *** [/tmp/erlang-build/make/run_make.mk:34: opt] Error 2
make[2]: Leaving directory '/tmp/erlang-build/erts/emulator'
make[1]: *** [Makefile:60: smp] Error 2
make[1]: Leaving directory '/tmp/erlang-build/erts'
make: *** [Makefile:443: emulator] Error 2
```
[here command cut]
The command '/bin/sh ...

**Comment by bitwalker** [comment]
You may need to adjust the build flags in the Dockerfile, I would start by removing `--enable-hipe`, as that's a likely culprit. The other one I'd try removing is `--enable-threads`.

**Comment by apischan** [comment]
Removing neither `--enable-hipe` nor `--enable-threads` helped. Exactly the same error. Can you give me the list of flags that needed for sure?

**Comment by apischan** [comment]
I've already removed all of the flags and still the same issue :(

**Comment by bitwalker** [comment]
It must have something to do with a system dependency then - you could try with an older version of Alpine, but I would suggest taking a look at the official Erlang image on Docker Hub, they have tags for 17.x, it might be a safer bet than trying to make my image work with 17.x.

**Comment by apischan** [comment]
The thing is that we have fixed version of alpine in base image. The same reason why I cannot take official image - we have fixed base image that is just almost pure alpine but I tried only pure alpine.
Looks that reason is lack of some module in alpine kernel. 
But anyway thank you for the desire to help :)

**Comment by bitwalker** [comment]
Ah, so you aren't using `alpine:3.5` as the base image, but something else? It definitely must be missing something present in the base image then, but perhaps it's a dependency you can install via `apk`?

Sorry I couldn't be of more help!

**Comment by apischan** [comment]
Actually I tried just your Dockerfile changing only the version of erlang....

**Comment by bitwalker** [comment]
Hmmm, I'll have to experiment and see if I can get it to work

**Comment by bitwalker** [comment]
So I added `--disable-kernel-poll` and changed to `--disable-hipe`, and it got a lot farther, but it breaks down the line a ways again. I suspect this is because the autoconf version installed in the image is newer than the one required by 17.5, because I can't think of any reason why disabling those two things is necessary with 17.5, but not 19.x.
