### ISSUE TITLE
Auto build docker image with version tag

### ISSUE THREAD

**Issue by oliver-kriska** [bitwalker/alpine-erlang#80]
Hello,

there is easy way how to build docker image with specific version of erlang (elixir). 
You just have to add this configuration to builds section in Docker Hub.
```
{\1}
/^v([0-9.]+)$/
```
![Screenshot 2020-07-22 at 11 50 58](https://user-images.githubusercontent.com/39122854/88162552-c469cd80-cc11-11ea-858d-76df9c3f5f71.png)

And when you make tag for example with this command:
```
git tag -a v23.0.3 -m "Erlang OTP 23.0.3" && git push origin v23.0.3
```
It will build image with that right tag and make nice history of builds in tags section of this github repo. 
_Note: Maybe there is better command to make git tag._

**Comment by bitwalker** [comment]
This is done as part of CI now
